# This workflow hard-tags and exports soft-tagged components
name: Tag and Export Components

on:
  pull_request:
    branches: [main]

jobs:
  tag-and-export:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '--skip-ci')"
    env:
      BIT_TOKEN: ${{ secrets.BIT_TOKEN }}

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: add some text
        run: echo "Hello Again with permissions " >> texttemp
      - name: Commit changes made to texttemp
        run: |
          git config --global user.name '${{ github.actor }}'
          git config --global user.email '${{ github.actor }}@users.noreply.github.com'
          git add texttemp
          git commit -m "update texttemp. --skip-ci"
          git pull origin HEAD:'${{ github.event.pull_request.head.ref }}'
          git push origin HEAD:'${{ github.event.pull_request.head.ref }}'

